import {
  Activity,
  AppWindow,
  ClipboardList,
  ScanText,
  Signature,
  Droplets,
  PaintBucket,
  BookOpen,
  Circle,
  Copy,
  FileDown,
  Combine,
  FilePlus2,
  PenLine as PenLineIcon,
  Highlighter,
  LayoutGrid,
  MessageSquare,
  MessageSquarePlus,
  Pencil,
  Square as SquareIcon,
  Stamp,
  Strikethrough,
  Type,
  Underline,
  TimerReset,
  Redo2,
  RotateCcwSquare,
  RotateCwSquare,
  Save,
  Trash,
  Undo2,
  ChevronDown,
  ChevronUp,
  ChevronsDown,
  ChevronsUp,
  ChevronDown as ChevronDownIcon,
  FolderOpen,
  Bookmark,
  ClipboardCopy,
  Eraser,
  Info,
  Keyboard,
  Layers,
  Maximize2,
  Monitor,
  Moon,
  Paperclip,
  PanelLeft,
  PanelRight,
  PanelTop,
  Maximize,
  MoveHorizontal,
  RotateCcw,
  RotateCw,
  Scan,
  Search,
  SearchX,
  Settings as SettingsIcon,
  SlidersHorizontal,
  SquareX,
  ZoomIn,
  ZoomOut,
  StickyNote,
  Sun,
} from 'lucide-react';
import type { AnnotationKind } from '@shared/schemas/annotation';
import type { LeftPanelId } from '@shared/schemas/settings';
import { CommandRegistry } from './registry';
import type { CommandAvailability, CommandContext, CommandDefinition } from './types';

const LEFT_PANELS: Array<{ id: LeftPanelId; title: string; icon: typeof Bookmark }> = [
  { id: 'pages', title: 'Page Thumbnails', icon: StickyNote },
  { id: 'bookmarks', title: 'Bookmarks', icon: Bookmark },
  { id: 'attachments', title: 'Attachments', icon: Paperclip },
  { id: 'layers', title: 'Layers', icon: Layers },
];

/** Commands that need a document in front of the reader. */
const documentRequired = (context: CommandContext): boolean | CommandAvailability =>
  context.activeDocument !== null ? true : { enabled: false, reason: 'No document is open.' };

function leftPanelCommands(): CommandDefinition[] {
  return LEFT_PANELS.map(({ id, title, icon }) => ({
    id: `view.show${id[0]?.toUpperCase() ?? ''}${id.slice(1)}`,
    title,
    description: `Show ${title.toLowerCase()} in the left panel.`,
    category: 'view' as const,
    group: 'panels',
    icon,
    keywords: ['panel', 'sidebar', id],
    isChecked: (context) =>
      context.settings.layout.leftPanel.visible && context.settings.layout.activeLeftPanel === id,
    run: (context) => context.actions.setLeftPanel(id),
  }));
}

/** The comment tools that are worth a command of their own. */
const ANNOTATION_TOOLS: Array<{
  tool: AnnotationKind | 'eraser';
  title: string;
  icon: typeof SquareIcon;
  keywords: string[];
}> = [
  { tool: 'highlight', title: 'Highlight Text', icon: Highlighter, keywords: ['mark', 'yellow'] },
  { tool: 'underline', title: 'Underline Text', icon: Underline, keywords: ['mark'] },
  {
    tool: 'strikeOut',
    title: 'Strike Through Text',
    icon: Strikethrough,
    keywords: ['mark', 'delete'],
  },
  { tool: 'note', title: 'Add Sticky Note', icon: MessageSquarePlus, keywords: ['comment'] },
  { tool: 'freeText', title: 'Add Text Box', icon: Type, keywords: ['typewriter', 'write'] },
  { tool: 'square', title: 'Draw Rectangle', icon: SquareIcon, keywords: ['shape', 'box'] },
  { tool: 'circle', title: 'Draw Ellipse', icon: Circle, keywords: ['shape', 'oval'] },
  { tool: 'ink', title: 'Draw Freehand', icon: Pencil, keywords: ['pen', 'ink', 'scribble'] },
  { tool: 'stamp', title: 'Add Stamp', icon: Stamp, keywords: ['approved', 'draft'] },
];

function annotationToolCommands(): CommandDefinition[] {
  return ANNOTATION_TOOLS.map(({ tool, title, icon, keywords }) => ({
    id: `tools.annotate.${tool}`,
    title,
    category: 'tools' as const,
    group: 'comment',
    icon,
    keywords: ['comment', 'annotation', ...keywords],
    isChecked: (context) => context.annotationTool === tool,
    isAvailable: documentRequired,
    run: (context) => context.actions.setAnnotationTool(tool),
  }));
}

/**
 * Every command PaperForge can run today.
 *
 * Commands are added by the segment that makes them work — nothing here is a
 * placeholder, so a menu or palette entry always does what it says.
 */
export function buildCommands(): CommandDefinition[] {
  return [
    {
      id: 'file.open',
      title: 'Open…',
      description: 'Open one or more PDF files from this computer.',
      category: 'file',
      group: 'open',
      icon: FolderOpen,
      shortcut: 'Ctrl+O',
      keywords: ['file', 'browse', 'document'],
      run: (context) => context.actions.openDocuments(),
    },
    {
      id: 'file.openInNewWindow',
      title: 'New Window',
      description: 'Open another PaperForge window.',
      category: 'file',
      group: 'open',
      icon: AppWindow,
      keywords: ['window', 'second'],
      run: (context) => context.actions.openInNewWindow(),
    },
    {
      id: 'file.revealInExplorer',
      title: 'Show in Explorer',
      description: 'Open the folder containing the active document.',
      category: 'file',
      group: 'document',
      icon: FolderOpen,
      keywords: ['folder', 'location', 'reveal'],
      isAvailable: (context) =>
        context.activeDocument !== null ? true : { enabled: false, reason: 'No document is open.' },
      run: (context) => context.actions.revealActiveDocument(),
    },
    {
      id: 'file.save',
      title: 'Save',
      description: 'Write the changes back to the file this document came from.',
      category: 'file',
      group: 'save',
      icon: Save,
      shortcut: 'Ctrl+S',
      keywords: ['write', 'store', 'keep'],
      isAvailable: (context) => {
        if (context.activeDocument === null) {
          return { enabled: false, reason: 'No document is open.' };
        }
        if (context.activeEdit?.dirty !== true) {
          return { enabled: false, reason: 'This document has no unsaved changes.' };
        }
        if (context.activeDocument.file.readOnly) {
          return { enabled: false, reason: 'This file is read-only. Use Save a Copy instead.' };
        }
        return true;
      },
      run: (context) => context.actions.saveDocument('save'),
    },
    {
      id: 'file.saveAs',
      title: 'Save As…',
      description: 'Write this document to a new file and keep working in it.',
      category: 'file',
      group: 'save',
      icon: FileDown,
      shortcut: 'Ctrl+Shift+S',
      keywords: ['rename', 'new file', 'another name'],
      isAvailable: documentRequired,
      run: (context) => context.actions.saveDocument('saveAs'),
    },
    {
      id: 'file.saveCopy',
      title: 'Save a Copy',
      description: 'Write a copy elsewhere and carry on in this document.',
      category: 'file',
      group: 'save',
      icon: Copy,
      keywords: ['duplicate', 'backup', 'export'],
      isAvailable: documentRequired,
      run: (context) => context.actions.saveDocument('saveCopy'),
    },
    {
      id: 'file.revert',
      title: 'Revert to Saved',
      description: 'Go back to the document as it was last saved. This can be undone.',
      category: 'file',
      group: 'save',
      icon: TimerReset,
      keywords: ['discard', 'undo all', 'reload'],
      isAvailable: (context) =>
        context.activeEdit?.dirty === true
          ? true
          : { enabled: false, reason: 'This document has no unsaved changes.' },
      run: (context) => context.actions.revert(),
    },
    {
      id: 'file.closeDocument',
      title: 'Close Document',
      category: 'file',
      group: 'document',
      icon: SquareX,
      shortcut: 'Ctrl+W',
      keywords: ['tab', 'close'],
      isAvailable: (context) =>
        context.activeDocument !== null ? true : { enabled: false, reason: 'No document is open.' },
      run: (context) => context.actions.closeActiveDocument(),
    },
    {
      id: 'file.closeAllDocuments',
      title: 'Close All Documents',
      category: 'file',
      group: 'document',
      icon: SquareX,
      keywords: ['tabs', 'close everything'],
      isAvailable: (context) =>
        context.openDocumentCount > 0 ? true : { enabled: false, reason: 'No document is open.' },
      run: (context) => context.actions.closeAllDocuments(),
    },
    {
      id: 'window.close',
      title: 'Close Window',
      category: 'file',
      group: 'window',
      icon: AppWindow,
      shortcut: 'Ctrl+Shift+W',
      keywords: ['quit', 'exit'],
      run: (context) => context.actions.closeWindow(),
    },
    {
      id: 'tools.edit',
      title: 'Edit PDF',
      description: 'Change the text a page draws, in the font that drew it.',
      category: 'tools',
      group: 'edit',
      icon: PenLineIcon,
      shortcut: 'Ctrl+E',
      keywords: ['text', 'rewrite', 'change', 'content'],
      isChecked: (context) => context.editingText,
      isAvailable: documentRequired,
      run: (context) => context.actions.toggleTextEditing(),
    },
    {
      id: 'tools.create',
      title: 'Create PDF',
      description: 'Make a document from images, text files, web pages or other PDFs.',
      category: 'tools',
      group: 'create',
      icon: FilePlus2,
      shortcut: 'Ctrl+N',
      keywords: ['new', 'blank', 'images', 'text', 'html', 'make'],
      isChecked: (context) => context.creating,
      run: (context) => context.actions.openCreateWorkspace('create'),
    },
    {
      id: 'tools.combine',
      title: 'Combine Files',
      description: 'Put several documents together, choosing the pages each one contributes.',
      category: 'tools',
      group: 'create',
      icon: Combine,
      keywords: ['merge', 'join', 'append', 'binder'],
      isChecked: (context) => context.creating,
      run: (context) => context.actions.openCreateWorkspace('combine'),
    },
    {
      id: 'tools.organize',
      title: 'Organize Pages',
      description: 'Rearrange, rotate, extract, split and insert pages.',
      category: 'tools',
      group: 'pages',
      icon: LayoutGrid,
      shortcut: 'Ctrl+Shift+P',
      keywords: ['pages', 'reorder', 'thumbnails', 'split', 'extract', 'insert', 'crop'],
      isChecked: (context) => context.organizing,
      isAvailable: documentRequired,
      run: (context) => context.actions.toggleOrganizing(),
    },
    {
      id: 'tools.comment',
      title: 'Comment',
      description: 'Show the comment tools and the properties of what you mark.',
      category: 'tools',
      group: 'comment',
      icon: MessageSquare,
      shortcut: 'Ctrl+M',
      keywords: ['annotate', 'markup', 'review', 'note'],
      isChecked: (context) => context.commenting,
      isAvailable: documentRequired,
      run: (context) => context.actions.toggleCommenting(),
    },
    ...annotationToolCommands(),
    {
      id: 'edit.deleteComment',
      title: 'Delete Comment',
      category: 'edit',
      group: 'comment',
      icon: Trash,
      keywords: ['annotation', 'remove'],
      isAvailable: (context) =>
        context.annotationSelected ? true : { enabled: false, reason: 'No comment is selected.' },
      run: (context) => context.actions.deleteSelectedAnnotation(),
    },
    {
      id: 'edit.resolveComment',
      title: 'Mark Comment Done',
      description: "PaperForge's own mark; other readers ignore it.",
      category: 'edit',
      group: 'comment',
      icon: MessageSquarePlus,
      keywords: ['resolve', 'status', 'done'],
      isAvailable: (context) =>
        context.annotationSelected ? true : { enabled: false, reason: 'No comment is selected.' },
      run: (context) => context.actions.toggleSelectedAnnotationResolved(),
    },
    {
      id: 'edit.undo',
      title: 'Undo',
      category: 'edit',
      group: 'history',
      icon: Undo2,
      shortcut: 'Ctrl+Z',
      keywords: ['back', 'revert', 'mistake'],
      isAvailable: (context) =>
        context.activeEdit?.canUndo === true
          ? true
          : { enabled: false, reason: 'There is nothing to undo.' },
      run: (context) => context.actions.undo(),
    },
    {
      id: 'edit.redo',
      title: 'Redo',
      category: 'edit',
      group: 'history',
      icon: Redo2,
      shortcut: 'Ctrl+Y',
      keywords: ['forward', 'again'],
      isAvailable: (context) =>
        context.activeEdit?.canRedo === true
          ? true
          : { enabled: false, reason: 'There is nothing to redo.' },
      run: (context) => context.actions.redo(),
    },
    {
      id: 'edit.rotatePageRight',
      title: 'Rotate Page Right',
      description: 'Turn this page a quarter clockwise in the document itself.',
      category: 'edit',
      group: 'pages',
      icon: RotateCwSquare,
      keywords: ['turn', 'page', 'clockwise', 'permanent'],
      isAvailable: documentRequired,
      run: (context) => context.actions.rotateCurrentPage(1),
    },
    {
      id: 'edit.rotatePageLeft',
      title: 'Rotate Page Left',
      description: 'Turn this page a quarter anticlockwise in the document itself.',
      category: 'edit',
      group: 'pages',
      icon: RotateCcwSquare,
      keywords: ['turn', 'page', 'anticlockwise', 'permanent'],
      isAvailable: documentRequired,
      run: (context) => context.actions.rotateCurrentPage(-1),
    },
    {
      id: 'edit.deletePage',
      title: 'Delete Page',
      description: 'Remove this page from the document. Undo brings it back.',
      category: 'edit',
      group: 'pages',
      icon: Trash,
      keywords: ['remove', 'page', 'drop'],
      isAvailable: (context) => {
        if (context.activeDocument === null) {
          return { enabled: false, reason: 'No document is open.' };
        }
        // A PDF has to keep at least one page.
        return context.activePageCount > 1
          ? true
          : { enabled: false, reason: 'A document must keep at least one page.' };
      },
      run: (context) => context.actions.deleteCurrentPage(),
    },
    {
      id: 'edit.find',
      title: 'Find',
      description: 'Search the text of this document.',
      category: 'edit',
      group: 'find',
      icon: Search,
      shortcut: 'Ctrl+F',
      keywords: ['search', 'text', 'locate'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openFind(),
    },
    {
      id: 'edit.findOptions',
      title: 'Find Options',
      description: 'Open find with the scope and page range options showing.',
      category: 'edit',
      group: 'find',
      icon: SlidersHorizontal,
      shortcut: 'Ctrl+H',
      keywords: ['search', 'advanced', 'range', 'scope'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openFind({ expandOptions: true }),
    },
    {
      id: 'edit.findNext',
      title: 'Find Next',
      category: 'edit',
      group: 'find',
      icon: ChevronDownIcon,
      shortcut: 'F3',
      keywords: ['search', 'next', 'forward'],
      isAvailable: (context) =>
        context.matchCount > 0 ? true : { enabled: false, reason: 'There are no matches.' },
      run: (context) => context.actions.findNext(),
    },
    {
      id: 'edit.findPrevious',
      title: 'Find Previous',
      category: 'edit',
      group: 'find',
      icon: ChevronUp,
      shortcut: 'Shift+F3',
      keywords: ['search', 'previous', 'back'],
      isAvailable: (context) =>
        context.matchCount > 0 ? true : { enabled: false, reason: 'There are no matches.' },
      run: (context) => context.actions.findPrevious(),
    },
    {
      id: 'edit.closeFind',
      title: 'Close Find',
      category: 'edit',
      group: 'find',
      icon: SearchX,
      keywords: ['search', 'hide', 'dismiss'],
      isAvailable: (context) =>
        context.findOpen ? true : { enabled: false, reason: 'The find bar is not open.' },
      run: (context) => context.actions.closeFind(),
    },
    {
      id: 'view.toggleLeftPanel',
      title: 'Left Panel',
      description: 'Show or hide the navigation panel.',
      category: 'view',
      group: 'layout',
      icon: PanelLeft,
      keywords: ['sidebar', 'navigation'],
      isChecked: (context) => context.settings.layout.leftPanel.visible,
      run: (context) =>
        context.actions.patchSettings({
          layout: { leftPanel: { visible: !context.settings.layout.leftPanel.visible } },
        }),
    },
    {
      id: 'view.toggleRightPanel',
      title: 'Tools Panel',
      description: 'Show or hide the properties and tools panel.',
      category: 'view',
      group: 'layout',
      icon: PanelRight,
      shortcut: 'F4',
      keywords: ['properties', 'tools'],
      isChecked: (context) => context.settings.layout.rightPanel.visible,
      run: (context) =>
        context.actions.patchSettings({
          layout: { rightPanel: { visible: !context.settings.layout.rightPanel.visible } },
        }),
    },
    {
      id: 'view.toggleCommandBar',
      title: 'Command Bar',
      description: 'Show or hide the menu bar.',
      category: 'view',
      group: 'layout',
      icon: PanelTop,
      keywords: ['toolbar', 'menu'],
      isChecked: (context) => context.settings.layout.commandBarVisible,
      run: (context) =>
        context.actions.patchSettings({
          layout: { commandBarVisible: !context.settings.layout.commandBarVisible },
        }),
    },
    ...leftPanelCommands(),
    {
      id: 'view.zoomIn',
      title: 'Zoom In',
      category: 'view',
      group: 'zoom',
      icon: ZoomIn,
      shortcut: 'Ctrl+=',
      keywords: ['magnify', 'larger'],
      isAvailable: documentRequired,
      run: (context) => context.actions.zoomBy(1),
    },
    {
      id: 'view.zoomOut',
      title: 'Zoom Out',
      category: 'view',
      group: 'zoom',
      icon: ZoomOut,
      shortcut: 'Ctrl+-',
      keywords: ['smaller'],
      isAvailable: documentRequired,
      run: (context) => context.actions.zoomBy(-1),
    },
    {
      id: 'view.fitPage',
      title: 'Fit Page',
      category: 'view',
      group: 'zoom',
      icon: Scan,
      shortcut: 'Ctrl+0',
      keywords: ['whole page', 'zoom'],
      isAvailable: documentRequired,
      isChecked: (context) => context.activeView?.zoomMode === 'fitPage',
      run: (context) => context.actions.setZoomMode('fitPage'),
    },
    {
      id: 'view.actualSize',
      title: 'Actual Size',
      category: 'view',
      group: 'zoom',
      icon: Maximize,
      shortcut: 'Ctrl+1',
      keywords: ['100%', 'zoom'],
      isAvailable: documentRequired,
      isChecked: (context) => context.activeView?.zoomMode === 'actual',
      run: (context) => context.actions.setZoomMode('actual'),
    },
    {
      id: 'view.fitWidth',
      title: 'Fit Width',
      category: 'view',
      group: 'zoom',
      icon: MoveHorizontal,
      shortcut: 'Ctrl+2',
      keywords: ['zoom'],
      isAvailable: documentRequired,
      isChecked: (context) => context.activeView?.zoomMode === 'fitWidth',
      run: (context) => context.actions.setZoomMode('fitWidth'),
    },
    {
      id: 'view.rotateLeft',
      title: 'Rotate View Left',
      description: 'Turns the view only; the document is not changed.',
      category: 'view',
      group: 'rotate',
      icon: RotateCcw,
      keywords: ['turn', 'landscape'],
      isAvailable: documentRequired,
      run: (context) => context.actions.rotateView(-1),
    },
    {
      id: 'view.rotateRight',
      title: 'Rotate View Right',
      description: 'Turns the view only; the document is not changed.',
      category: 'view',
      group: 'rotate',
      icon: RotateCw,
      keywords: ['turn', 'landscape'],
      isAvailable: documentRequired,
      run: (context) => context.actions.rotateView(1),
    },
    {
      id: 'view.nextPage',
      title: 'Next Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronDown,
      keywords: ['page', 'forward'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToRelativePage(1),
    },
    {
      id: 'view.previousPage',
      title: 'Previous Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronUp,
      keywords: ['page', 'back'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToRelativePage(-1),
    },
    {
      id: 'view.firstPage',
      title: 'First Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronsUp,
      keywords: ['start', 'top'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToPage(1),
    },
    {
      id: 'view.lastPage',
      title: 'Last Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronsDown,
      keywords: ['end', 'bottom'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToPage(Number.MAX_SAFE_INTEGER),
    },
    {
      id: 'view.toggleFullScreen',
      title: 'Full Screen',
      description: 'Fill the display with the workspace.',
      category: 'view',
      group: 'display',
      icon: Maximize2,
      shortcut: 'F11',
      keywords: ['reading mode', 'presentation'],
      isChecked: (context) => context.fullScreen,
      run: (context) => context.actions.toggleFullScreen(),
    },
    {
      id: 'view.readingMode',
      title: 'Reading Mode',
      description: 'Show only the document: no bars, rail or panels. Esc leaves it.',
      category: 'view',
      group: 'display',
      icon: BookOpen,
      shortcut: 'Ctrl+Shift+R',
      keywords: ['distraction', 'focus', 'presentation', 'clean'],
      isChecked: (context) => context.readingMode,
      isAvailable: documentRequired,
      run: (context) => context.actions.toggleReadingMode(),
    },
    {
      id: 'view.cycleRegions',
      title: 'Next Region',
      description: 'Move focus to the next major region of the window.',
      category: 'view',
      group: 'display',
      icon: Keyboard,
      shortcut: 'F6',
      keywords: ['focus', 'accessibility', 'keyboard'],
      run: (context) => context.actions.focusNextRegion(),
    },
    {
      id: 'theme.setSystem',
      title: 'Appearance: Follow Windows',
      category: 'view',
      group: 'appearance',
      icon: Monitor,
      keywords: ['theme', 'dark', 'light', 'system'],
      isChecked: (context) => context.settings.appearance.theme === 'system',
      run: (context) => context.actions.setThemePreference('system'),
    },
    {
      id: 'theme.setLight',
      title: 'Appearance: Light',
      category: 'view',
      group: 'appearance',
      icon: Sun,
      keywords: ['theme'],
      isChecked: (context) => context.settings.appearance.theme === 'light',
      run: (context) => context.actions.setThemePreference('light'),
    },
    {
      id: 'theme.setDark',
      title: 'Appearance: Dark',
      category: 'view',
      group: 'appearance',
      icon: Moon,
      keywords: ['theme', 'night'],
      isChecked: (context) => context.settings.appearance.theme === 'dark',
      run: (context) => context.actions.setThemePreference('dark'),
    },

    {
      id: 'app.commandPalette',
      title: 'Command Palette',
      description: 'Search every available command.',
      category: 'tools',
      group: 'app',
      icon: Search,
      shortcut: 'Ctrl+K',
      keywords: ['search', 'run', 'actions'],
      hiddenInPalette: true,
      run: (context) => context.actions.setCommandPaletteOpen(true),
    },
    {
      id: 'tools.fillSign',
      title: 'Fill & Sign',
      description: 'Complete form fields and add a simple signature.',
      category: 'tools',
      group: 'forms',
      icon: Signature,
      shortcut: 'Ctrl+Shift+F',
      keywords: ['form', 'field', 'sign', 'signature', 'fill in'],
      isChecked: (context) => context.filling,
      isAvailable: documentRequired,
      run: (context) => context.actions.toggleFilling(),
    },
    {
      id: 'tools.prepareForm',
      title: 'Prepare Form',
      description: 'Add fields, checkboxes and buttons to a document.',
      category: 'tools',
      group: 'forms',
      icon: ClipboardList,
      keywords: ['form', 'field', 'checkbox', 'author', 'design'],
      isChecked: (context) => context.preparingForm,
      isAvailable: documentRequired,
      run: (context) => context.actions.togglePreparingForm(),
    },
    {
      id: 'tools.ocr',
      title: 'Recognize Text',
      description: 'Read the words on a scanned page, entirely on this computer.',
      category: 'tools',
      group: 'content',
      icon: ScanText,
      keywords: ['ocr', 'scan', 'searchable', 'tesseract', 'text'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openDialog('ocr'),
    },
    {
      id: 'tools.watermark',
      title: 'Watermark',
      description: 'Draw a word or a picture over the pages, or under them.',
      category: 'tools',
      group: 'content',
      icon: Droplets,
      keywords: ['stamp', 'draft', 'confidential', 'overlay', 'background'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openDialog('watermark'),
    },
    {
      id: 'tools.background',
      title: 'Background',
      description: 'Put a colour or a picture under everything the pages draw.',
      category: 'tools',
      group: 'content',
      icon: PaintBucket,
      keywords: ['colour', 'color', 'paper', 'behind', 'watermark'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openDialog('background'),
    },
    {
      id: 'tools.headerFooter',
      title: 'Header and Footer',
      description: 'Add page numbers, dates, titles and Bates numbering.',
      category: 'tools',
      group: 'content',
      icon: PanelTop,
      keywords: ['page number', 'numbering', 'bates', 'date', 'title', 'footer'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openDialog('headerFooter'),
    },
    {
      id: 'app.openSettings',
      title: 'Settings',
      description: 'Open PaperForge settings.',
      category: 'tools',
      group: 'app',
      icon: SettingsIcon,
      shortcut: 'Ctrl+,',
      keywords: ['preferences', 'options'],
      run: (context) => context.actions.openDialog('settings'),
    },
    {
      id: 'app.toggleProgressCenter',
      title: 'Background Tasks',
      description: 'Show progress for long-running work.',
      category: 'tools',
      group: 'app',
      icon: Activity,
      keywords: ['jobs', 'progress', 'tasks'],
      run: (context) => context.actions.toggleProgressCenter(),
    },
    {
      id: 'privacy.clearRecentFiles',
      title: 'Clear Recent Files',
      description: 'Forget the list of recently opened files on this computer.',
      category: 'tools',
      group: 'privacy',
      icon: Eraser,
      keywords: ['privacy', 'history', 'forget'],
      isAvailable: (context) =>
        context.recentFiles.length > 0
          ? true
          : { enabled: false, reason: 'There are no recent files to clear.' },
      run: async (context) => {
        await context.actions.clearRecentFiles();
        context.actions.showToast({ title: 'Recent files cleared.', intent: 'success' });
      },
    },

    {
      id: 'help.about',
      title: 'About PaperForge',
      category: 'help',
      group: 'about',
      icon: Info,
      keywords: ['version', 'licenses'],
      run: (context) => context.actions.openDialog('about'),
    },
    {
      id: 'help.copyDiagnostics',
      title: 'Copy Diagnostics',
      description: 'Copy version and environment details to the clipboard.',
      category: 'help',
      group: 'about',
      icon: ClipboardCopy,
      keywords: ['support', 'environment', 'clipboard'],
      isAvailable: (context) =>
        context.appInfo !== null
          ? true
          : { enabled: false, reason: 'Environment details are still loading.' },
      run: (context) => context.actions.copyDiagnostics(),
    },
  ];
}

export function createCommandRegistry(): CommandRegistry {
  const registry = new CommandRegistry();
  registry.registerAll(buildCommands());
  return registry;
}
