import {
  Activity,
  AppWindow,
  ChevronDown,
  ChevronUp,
  ChevronsDown,
  ChevronsUp,
  ChevronDown as ChevronDownIcon,
  FolderOpen,
  Bookmark,
  ClipboardCopy,
  Eraser,
  Info,
  Keyboard,
  Layers,
  Maximize2,
  Monitor,
  Moon,
  Paperclip,
  PanelLeft,
  PanelRight,
  PanelTop,
  Maximize,
  MoveHorizontal,
  RotateCcw,
  RotateCw,
  Scan,
  Search,
  SearchX,
  Settings as SettingsIcon,
  SlidersHorizontal,
  SquareX,
  ZoomIn,
  ZoomOut,
  StickyNote,
  Sun,
} from 'lucide-react';
import type { LeftPanelId } from '@shared/schemas/settings';
import { CommandRegistry } from './registry';
import type { CommandAvailability, CommandContext, CommandDefinition } from './types';

const LEFT_PANELS: Array<{ id: LeftPanelId; title: string; icon: typeof Bookmark }> = [
  { id: 'pages', title: 'Page Thumbnails', icon: StickyNote },
  { id: 'bookmarks', title: 'Bookmarks', icon: Bookmark },
  { id: 'attachments', title: 'Attachments', icon: Paperclip },
  { id: 'layers', title: 'Layers', icon: Layers },
];

/** Commands that need a document in front of the reader. */
const documentRequired = (context: CommandContext): boolean | CommandAvailability =>
  context.activeDocument !== null ? true : { enabled: false, reason: 'No document is open.' };

function leftPanelCommands(): CommandDefinition[] {
  return LEFT_PANELS.map(({ id, title, icon }) => ({
    id: `view.show${id[0]?.toUpperCase() ?? ''}${id.slice(1)}`,
    title,
    description: `Show ${title.toLowerCase()} in the left panel.`,
    category: 'view' as const,
    group: 'panels',
    icon,
    keywords: ['panel', 'sidebar', id],
    isChecked: (context) =>
      context.settings.layout.leftPanel.visible && context.settings.layout.activeLeftPanel === id,
    run: (context) => context.actions.setLeftPanel(id),
  }));
}

/**
 * Every command PaperForge can run today.
 *
 * Commands are added by the segment that makes them work — nothing here is a
 * placeholder, so a menu or palette entry always does what it says.
 */
export function buildCommands(): CommandDefinition[] {
  return [
    {
      id: 'file.open',
      title: 'Open…',
      description: 'Open one or more PDF files from this computer.',
      category: 'file',
      group: 'open',
      icon: FolderOpen,
      shortcut: 'Ctrl+O',
      keywords: ['file', 'browse', 'document'],
      run: (context) => context.actions.openDocuments(),
    },
    {
      id: 'file.openInNewWindow',
      title: 'New Window',
      description: 'Open another PaperForge window.',
      category: 'file',
      group: 'open',
      icon: AppWindow,
      keywords: ['window', 'second'],
      run: (context) => context.actions.openInNewWindow(),
    },
    {
      id: 'file.revealInExplorer',
      title: 'Show in Explorer',
      description: 'Open the folder containing the active document.',
      category: 'file',
      group: 'document',
      icon: FolderOpen,
      keywords: ['folder', 'location', 'reveal'],
      isAvailable: (context) =>
        context.activeDocument !== null ? true : { enabled: false, reason: 'No document is open.' },
      run: (context) => context.actions.revealActiveDocument(),
    },
    {
      id: 'file.closeDocument',
      title: 'Close Document',
      category: 'file',
      group: 'document',
      icon: SquareX,
      shortcut: 'Ctrl+W',
      keywords: ['tab', 'close'],
      isAvailable: (context) =>
        context.activeDocument !== null ? true : { enabled: false, reason: 'No document is open.' },
      run: (context) => context.actions.closeActiveDocument(),
    },
    {
      id: 'file.closeAllDocuments',
      title: 'Close All Documents',
      category: 'file',
      group: 'document',
      icon: SquareX,
      keywords: ['tabs', 'close everything'],
      isAvailable: (context) =>
        context.openDocumentCount > 0 ? true : { enabled: false, reason: 'No document is open.' },
      run: (context) => context.actions.closeAllDocuments(),
    },
    {
      id: 'window.close',
      title: 'Close Window',
      category: 'file',
      group: 'window',
      icon: AppWindow,
      shortcut: 'Ctrl+Shift+W',
      keywords: ['quit', 'exit'],
      run: (context) => context.actions.closeWindow(),
    },
    {
      id: 'edit.find',
      title: 'Find',
      description: 'Search the text of this document.',
      category: 'edit',
      group: 'find',
      icon: Search,
      shortcut: 'Ctrl+F',
      keywords: ['search', 'text', 'locate'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openFind(),
    },
    {
      id: 'edit.findOptions',
      title: 'Find Options',
      description: 'Open find with the scope and page range options showing.',
      category: 'edit',
      group: 'find',
      icon: SlidersHorizontal,
      shortcut: 'Ctrl+H',
      keywords: ['search', 'advanced', 'range', 'scope'],
      isAvailable: documentRequired,
      run: (context) => context.actions.openFind({ expandOptions: true }),
    },
    {
      id: 'edit.findNext',
      title: 'Find Next',
      category: 'edit',
      group: 'find',
      icon: ChevronDownIcon,
      shortcut: 'F3',
      keywords: ['search', 'next', 'forward'],
      isAvailable: (context) =>
        context.matchCount > 0 ? true : { enabled: false, reason: 'There are no matches.' },
      run: (context) => context.actions.findNext(),
    },
    {
      id: 'edit.findPrevious',
      title: 'Find Previous',
      category: 'edit',
      group: 'find',
      icon: ChevronUp,
      shortcut: 'Shift+F3',
      keywords: ['search', 'previous', 'back'],
      isAvailable: (context) =>
        context.matchCount > 0 ? true : { enabled: false, reason: 'There are no matches.' },
      run: (context) => context.actions.findPrevious(),
    },
    {
      id: 'edit.closeFind',
      title: 'Close Find',
      category: 'edit',
      group: 'find',
      icon: SearchX,
      keywords: ['search', 'hide', 'dismiss'],
      isAvailable: (context) =>
        context.findOpen ? true : { enabled: false, reason: 'The find bar is not open.' },
      run: (context) => context.actions.closeFind(),
    },
    {
      id: 'view.toggleLeftPanel',
      title: 'Left Panel',
      description: 'Show or hide the navigation panel.',
      category: 'view',
      group: 'layout',
      icon: PanelLeft,
      keywords: ['sidebar', 'navigation'],
      isChecked: (context) => context.settings.layout.leftPanel.visible,
      run: (context) =>
        context.actions.patchSettings({
          layout: { leftPanel: { visible: !context.settings.layout.leftPanel.visible } },
        }),
    },
    {
      id: 'view.toggleRightPanel',
      title: 'Tools Panel',
      description: 'Show or hide the properties and tools panel.',
      category: 'view',
      group: 'layout',
      icon: PanelRight,
      shortcut: 'F4',
      keywords: ['properties', 'tools'],
      isChecked: (context) => context.settings.layout.rightPanel.visible,
      run: (context) =>
        context.actions.patchSettings({
          layout: { rightPanel: { visible: !context.settings.layout.rightPanel.visible } },
        }),
    },
    {
      id: 'view.toggleCommandBar',
      title: 'Command Bar',
      description: 'Show or hide the menu bar.',
      category: 'view',
      group: 'layout',
      icon: PanelTop,
      keywords: ['toolbar', 'menu'],
      isChecked: (context) => context.settings.layout.commandBarVisible,
      run: (context) =>
        context.actions.patchSettings({
          layout: { commandBarVisible: !context.settings.layout.commandBarVisible },
        }),
    },
    ...leftPanelCommands(),
    {
      id: 'view.zoomIn',
      title: 'Zoom In',
      category: 'view',
      group: 'zoom',
      icon: ZoomIn,
      shortcut: 'Ctrl+=',
      keywords: ['magnify', 'larger'],
      isAvailable: documentRequired,
      run: (context) => context.actions.zoomBy(1),
    },
    {
      id: 'view.zoomOut',
      title: 'Zoom Out',
      category: 'view',
      group: 'zoom',
      icon: ZoomOut,
      shortcut: 'Ctrl+-',
      keywords: ['smaller'],
      isAvailable: documentRequired,
      run: (context) => context.actions.zoomBy(-1),
    },
    {
      id: 'view.fitPage',
      title: 'Fit Page',
      category: 'view',
      group: 'zoom',
      icon: Scan,
      shortcut: 'Ctrl+0',
      keywords: ['whole page', 'zoom'],
      isAvailable: documentRequired,
      isChecked: (context) => context.activeView?.zoomMode === 'fitPage',
      run: (context) => context.actions.setZoomMode('fitPage'),
    },
    {
      id: 'view.actualSize',
      title: 'Actual Size',
      category: 'view',
      group: 'zoom',
      icon: Maximize,
      shortcut: 'Ctrl+1',
      keywords: ['100%', 'zoom'],
      isAvailable: documentRequired,
      isChecked: (context) => context.activeView?.zoomMode === 'actual',
      run: (context) => context.actions.setZoomMode('actual'),
    },
    {
      id: 'view.fitWidth',
      title: 'Fit Width',
      category: 'view',
      group: 'zoom',
      icon: MoveHorizontal,
      shortcut: 'Ctrl+2',
      keywords: ['zoom'],
      isAvailable: documentRequired,
      isChecked: (context) => context.activeView?.zoomMode === 'fitWidth',
      run: (context) => context.actions.setZoomMode('fitWidth'),
    },
    {
      id: 'view.rotateLeft',
      title: 'Rotate View Left',
      description: 'Turns the view only; the document is not changed.',
      category: 'view',
      group: 'rotate',
      icon: RotateCcw,
      keywords: ['turn', 'landscape'],
      isAvailable: documentRequired,
      run: (context) => context.actions.rotateView(-1),
    },
    {
      id: 'view.rotateRight',
      title: 'Rotate View Right',
      description: 'Turns the view only; the document is not changed.',
      category: 'view',
      group: 'rotate',
      icon: RotateCw,
      keywords: ['turn', 'landscape'],
      isAvailable: documentRequired,
      run: (context) => context.actions.rotateView(1),
    },
    {
      id: 'view.nextPage',
      title: 'Next Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronDown,
      keywords: ['page', 'forward'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToRelativePage(1),
    },
    {
      id: 'view.previousPage',
      title: 'Previous Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronUp,
      keywords: ['page', 'back'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToRelativePage(-1),
    },
    {
      id: 'view.firstPage',
      title: 'First Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronsUp,
      keywords: ['start', 'top'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToPage(1),
    },
    {
      id: 'view.lastPage',
      title: 'Last Page',
      category: 'view',
      group: 'navigate',
      icon: ChevronsDown,
      keywords: ['end', 'bottom'],
      isAvailable: documentRequired,
      run: (context) => context.actions.goToPage(Number.MAX_SAFE_INTEGER),
    },
    {
      id: 'view.toggleFullScreen',
      title: 'Full Screen',
      description: 'Fill the display with the workspace.',
      category: 'view',
      group: 'display',
      icon: Maximize2,
      shortcut: 'F11',
      keywords: ['reading mode', 'presentation'],
      isChecked: (context) => context.fullScreen,
      run: (context) => context.actions.toggleFullScreen(),
    },
    {
      id: 'view.cycleRegions',
      title: 'Next Region',
      description: 'Move focus to the next major region of the window.',
      category: 'view',
      group: 'display',
      icon: Keyboard,
      shortcut: 'F6',
      keywords: ['focus', 'accessibility', 'keyboard'],
      run: (context) => context.actions.focusNextRegion(),
    },
    {
      id: 'theme.setSystem',
      title: 'Appearance: Follow Windows',
      category: 'view',
      group: 'appearance',
      icon: Monitor,
      keywords: ['theme', 'dark', 'light', 'system'],
      isChecked: (context) => context.settings.appearance.theme === 'system',
      run: (context) => context.actions.setThemePreference('system'),
    },
    {
      id: 'theme.setLight',
      title: 'Appearance: Light',
      category: 'view',
      group: 'appearance',
      icon: Sun,
      keywords: ['theme'],
      isChecked: (context) => context.settings.appearance.theme === 'light',
      run: (context) => context.actions.setThemePreference('light'),
    },
    {
      id: 'theme.setDark',
      title: 'Appearance: Dark',
      category: 'view',
      group: 'appearance',
      icon: Moon,
      keywords: ['theme', 'night'],
      isChecked: (context) => context.settings.appearance.theme === 'dark',
      run: (context) => context.actions.setThemePreference('dark'),
    },

    {
      id: 'app.commandPalette',
      title: 'Command Palette',
      description: 'Search every available command.',
      category: 'tools',
      group: 'app',
      icon: Search,
      shortcut: 'Ctrl+K',
      keywords: ['search', 'run', 'actions'],
      hiddenInPalette: true,
      run: (context) => context.actions.setCommandPaletteOpen(true),
    },
    {
      id: 'app.openSettings',
      title: 'Settings',
      description: 'Open PaperForge settings.',
      category: 'tools',
      group: 'app',
      icon: SettingsIcon,
      shortcut: 'Ctrl+,',
      keywords: ['preferences', 'options'],
      run: (context) => context.actions.openDialog('settings'),
    },
    {
      id: 'app.toggleProgressCenter',
      title: 'Background Tasks',
      description: 'Show progress for long-running work.',
      category: 'tools',
      group: 'app',
      icon: Activity,
      keywords: ['jobs', 'progress', 'tasks'],
      run: (context) => context.actions.toggleProgressCenter(),
    },
    {
      id: 'privacy.clearRecentFiles',
      title: 'Clear Recent Files',
      description: 'Forget the list of recently opened files on this computer.',
      category: 'tools',
      group: 'privacy',
      icon: Eraser,
      keywords: ['privacy', 'history', 'forget'],
      isAvailable: (context) =>
        context.recentFiles.length > 0
          ? true
          : { enabled: false, reason: 'There are no recent files to clear.' },
      run: async (context) => {
        await context.actions.clearRecentFiles();
        context.actions.showToast({ title: 'Recent files cleared.', intent: 'success' });
      },
    },

    {
      id: 'help.about',
      title: 'About PaperForge',
      category: 'help',
      group: 'about',
      icon: Info,
      keywords: ['version', 'licenses'],
      run: (context) => context.actions.openDialog('about'),
    },
    {
      id: 'help.copyDiagnostics',
      title: 'Copy Diagnostics',
      description: 'Copy version and environment details to the clipboard.',
      category: 'help',
      group: 'about',
      icon: ClipboardCopy,
      keywords: ['support', 'environment', 'clipboard'],
      isAvailable: (context) =>
        context.appInfo !== null
          ? true
          : { enabled: false, reason: 'Environment details are still loading.' },
      run: (context) => context.actions.copyDiagnostics(),
    },
  ];
}

export function createCommandRegistry(): CommandRegistry {
  const registry = new CommandRegistry();
  registry.registerAll(buildCommands());
  return registry;
}
